name: Bug report
description: Report incorrect or unexpected behavior
labels: [bug report]
body:
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: |
        Describe the issue in as much detail as possible.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files into it.
      placeholder: |
        Steps to reproduce with below code sample:
        1. do thing
        2. do thing in Discord client
        3. observe behavior
        4. see error logs below
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Which environment is concerned?
      description: |
        Production: https://linkfy.fr
        Development : https://preview.linkfy.fr
      options:
        - Production
        - Development
      multiple: true
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority this issue should have
      description: Please be realistic. If you need to elaborate on your reasoning, please use the Issue description field above.
      options:
        - Low (slightly annoying)
        - Medium (should be fixed soon)
        - High (immediate attention needed)
    validations:
      required: true
  - type: input
    id: dev-release
    attributes:
      label: I have tested this issue on a development release (Development environment)
      placeholder: f9014df (commit hash)
      description: |
        Is not required but it can be useful 