name: Feature request
description: Request a new feature
labels: [feature request]
body:
  - type: dropdown
    id: account-types
    attributes:
      label: For you, it would be for whom? 
      options:
        - Free users
        - Pro users
        - No account users (include free users)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Feature
      description: A clear and concise description of what the problem is, or what feature you want to be implemented.
      placeholder: An button for [...]
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Other context
      description: Any other context, screenshots, or file uploads that help us understand your feature request.
