name: Need answers
description: To ask questions
labels: [help]
body:
  - type: dropdown
    id: subject
    attributes:
      label: On what subject?
      description: |
        Indicate here the subject of the question so that we can better identify the answer
      options:
        - Feature
        - Functioning
        - Other
      multiple: true
    validations:
      required: true
  - type: textarea
    id: questions
    attributes:
      label: Ask your questions here
      description: No limit, but try to be clear and don't beat around the bush, ask direct questions  
